dist: xenial
language: python
python:
    - "2.7"
    - "3.6"

env:
    - PADDLE_VER="paddlepaddle"

install:
    - export MPLBACKEND=Agg
    - sudo apt-get update
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - which python
    - pip install future
    - pip install numpy
    - pip install protobuf==3.8.0
    - pip install six
    - pip install pillow
    - pip install moviepy
    - pip install matplotlib
    - pip install requests
    - pip install tb-nightly
    - pip install crc32c
    - pip install flake8
    - pip install paddlepaddle
    - conda list
    - python setup.py install

script:
    - cd API_demo
    - python add_scalar-demo.py
    - python add_histogram-demo.py
    - python add_text-demo.py
    - python add_image-demo.py
    - python add_audio-demo.py
    - python add_custom_scalars-demo.py
    - python add_pr_curve-demo.py
    - python add_paddle_graph-demo.py
    
after_success:
    - sleep 1
