language: python

python:
    - "2.7"
    - "3.6"

env:
    - PADDLE_VER="paddlepaddle"

install:
    - sudo apt-get update
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi  
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - conda activate test-environment
    - which python
    - pip install future
    - pip install chainer -q
    - pip install moviepy==0.2.3.2 -q
    - pip install matplotlib -q
    - pip install requests -q
    - pip install codecov
    - pip install boto3
    - pip install moto
    - pip install visdom
    - pip install tb-nightly
    - pip install crc32c
    - pip install protobuf==3.8.0
    - pip install ffmpeg
    - python setup.py install

script:
    - sleep 1

notifications:
  email:
    on_success: change
    on_failure: always
